In [1]:
x = [1,2,3,4]
y = [4,5,6,7]
z =[]
for i,j in zip(x,y):
    z.append(i+j)
print(z)

[5, 7, 9, 11]


In [ ]:
#vectorized version using numpy, instead of for loop
import numpy as np
x = [1,2,3,4]
y = [4,5,6,7]

z = np.add(x,y)
print(z)

[ 5  7  9 11]


In [ ]:
#CREATING MY OWN UNFUCNTION ADDITION FUNCTION
import numpy as np
def add(x,y):
    return x+y

myadd = np.frompyfunc(add,2,1)
print(myadd([1,2,3,4],[5,6,7,8]))

[6 8 10 12]


In [3]:
#CREATING MY OWN UNFUCNTION SUBTRACTION FUNCTION
import numpy as np
def sub(x,y):
    return y-x
mysub = np.frompyfunc(sub,2,1) #frompyfunc() is used to add it to my numpy unfunc library
print(mysub([1,2,3,4],[5,6,7,8]))


[4 4 4 4]


In [5]:
#UNFUNC ARITHMETIC
import numpy as np

#ADDITION
arr1= np.array([1,2,3,4,5])
arr2= np.array([6,7,8,9,10])
new_arr = np.add(arr1,arr2)
print(new_arr)

#SUBSTRACTION
arr1= np.array([1,2,3,4,5])
arr2= np.array([6,7,8,9,10])
new_arr = np.subtract(arr2,arr1)
print(new_arr)

#MULTIPLICATION
arr1= np.array([1,2,3,4,5])
arr2= np.array([6,7,8,9,10])
new_arr = np.multiply(arr2,arr1)
print(new_arr)


[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]


In [7]:
#LOG UNFUNC
import numpy as np

arr = np.arange(1,11)
print(np.log10(arr))
print(np.log(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [12]:
#SUMMATION
import numpy as np
arr1= np.array([1,2,3,4,5])
arr2= np.array([6,7,8,9,10])
new_arr = np.sum([arr1,arr2])
print(new_arr)

55


In [13]:
#SUMMATION OVER AN AXIS
import numpy as np
arr1= np.array([1,2,3,4,5])
arr2= np.array([6,7,8,9,10])
new_arr = np.sum([arr1,arr2],axis=1)
print(new_arr)

[15 40]


In [14]:
#CUMMULATIVE SUM
import numpy as np
arr1= np.array([1,2,3,4,5])
arr2= np.array([6,7,8,9,10])
new_arr = np.cumsum([arr1,arr2])
print(new_arr)

[ 1  3  6 10 15 21 28 36 45 55]


In [15]:
#TRIGONOMETRIC FUNCTIONS
import numpy as np
arr = np.array([np.pi/2,np.pi/3,np.pi/3,np.pi/4])
new_arr = np.sin(arr)
print(new_arr)

[1.         0.8660254  0.8660254  0.70710678]


In [ ]:
#SETS
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)